### ISSUE TITLE
Pragmatic and semantic quality criteria

### ISSUE THREAD

**Issue by gunturbudi** [RELabUU/aqusa-core#3]
Dear RE Lab teams,

I wonder whether there is development ongoing on the pragmatic and semantic quality criteria?

Thanks!

**Comment by fabianodalp** [comment]
Hello @gunturbudi . Sorry I did not respond to this thread, I don't seem to get notifications. No updates on those, but if you are willing to collaborate on these topics, let me know (reach out to me via f.dalpiaz@uu.nl)
